### ISSUE TITLE
Error After Plugin Update

### ISSUE THREAD

**Issue by andrelauz** [FrenetGatewaydeFretes/woo-shipping-gateway#17] opened 2022-09-29 20:35 UTC
Hello everyone!

After updating woo-shipping-gateway I came across the following error. Has anyone run into the same problem?

Link: https://rootstockvinhos.com.br/

2022/09/29 17:04:49 [error] 2032341#0: *621977 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined property: stdClass::$ShippingSevicesArray in /var/www/html/interno/plugins/woo-shipping-gateway/includes/class-wc-frenet.php on line 564PHP message: PHP Warning:  Attempt to read property "ShippingSevices" on null in /var/www/html/interno/plugins/woo-shipping-gateway/includes/class-wc-frenet.php on line 564PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/interno/plugins/woo-shipping-gateway/includes/class-wc-frenet.php:564
Stack trace:
#0 /var/www/html/interno/plugins/woo-shipping-gateway/includes/class-wc-frenet.php(311): WC_Frenet->frenet_calculate()
#1 /var/www/html/interno/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(233): WC_Frenet->calculate_shipping()
#2 /var/www/html/interno/plugins/woocommerce/includes/class-wc-shipping.php(348): WC_Shipping_Method->get_rates_for_package()
#3 /var/www/html/interno/plugins/woocommerce/includes/class-wc-shipping.php(260): WC_Shipping->calculate_shipping_for_package()
#4 /var/www/html/interno/plugins/woocommerce/includes/class-wc-cart.php(1420): WC_Shipping->calculate_shipping()
#5 /var/www/html/interno/plugins/woocommerce/includes/class-wc-cart-totals.php(339): WC_Cart->calculate_shipping()
#6 /var/www/html/interno/plugins/woocommerce/include" while reading response header from upstream, client: 177.96.126.110, server: rootstockvinhos.com.br, request: "GET /carrinho/ HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "rootstockvinhos.com.br", referrer: "https://rootstockvinhos.com.br/"

**Comment by alexandercamps** [comment] 2022-11-03 12:54
Hi There!
We apreciate your comment, but let us explain the cause.

There is in Frenet 2 way for quotation SOAP WS (legacy) and REST API.

When you setting Token the plug-in call REST API Frenet, but not setting the Token SOAP WS is called.

The problem was validated just in the SOAP WS response, so the problem was resolved and a new version will be released soon, but kindly to do the adjust for Token, in this case the problem doesn´t exists.

Regards,

**Closed** 2022-11-09 02:02 UTC
